strategy:
  matrix:
    Mac:
      imageName: 'macos-10.13'
      toolchain: stable
    Windows:
      imageName: 'vs2017-win2016'
      toolchain: stable-i686-pc-windows-msvc
    Linux:
      imageName: 'ubuntu-16.04'
      toolchain: stable

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install Rust on non-Windows
    env:
      TOOLCHAIN: $()
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --default-toolchain %TOOLCHAIN%
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    displayName: Install Rust on Windows
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - script: cargo build --all
    displayName: Cargo build
  - script: cargo test --all
    displayName: Cargo test
  - script: npm install
    displayName: Install JS dependencies
  - script: npm test
    displayName: Run JS tests
