[package]
name = "notify-subprocess"
version = "0.1.0"
edition = "2018"

[dependencies]
dunce = "1.0"
notify = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.2"
